<!--<div class="menu" id="menu">
         <form method="POST" name="formLogin" id="formLogin" <?php /*action="/usuarios/validar"*/ ?>>
                <select class="chzn-select" name="language_list" onchange="javascript: jumpMenu('parent',this,0);" style="display: none; ">
                <select class="chzn-select" name="language_list"  style="display: none; ">
                        <option value="/tesiss/index.php?language=bulgarian">A</option>
                        <option value="/tesiss/index.php?language=bulgarian">B</option>
                </select>				

                <br/>
                <div>
                        <label>Nombre de Usuario</label>
                </div>
                <div>
                        <input size="17" name="iduser" type="text">
                </div>
                <div>
                        <label>Contraseña</label>
                </div>
                <div>
                        <input size="17" name="password" type="password">
                </div>
                <div>
                        <label></label>
                </div>
                <div>
                        <input class="login" id="botoncito" name="submitAuth" type="submit" value="Ingresar"/>
                </div>
                <input name="opt" type="hidden" value="validar">
                <div class="clear">
                &nbsp;
                </div>

        </form>
        <div id="mensaje">
        </div>
        <div class="menusection">
                <span class="menusectioncaption">Usuario</span>
                <ul class="menulist">
                        <li>
                                <input type="checkbox"> <a>Recordarme</a></input>
                        </li>
                        <li>
                                <a href="/main/auth/lostPassword.php">¿Ha olvidado su contraseña?</a>
                        </li>
                </ul>
        </div>
</div>-->

<body>
    <div id="wrapper">
        <ul id="navigation">
            <li class="report">
                <a href="#" target="_blank" style="margin-left: 50px; ">
                    <img src="/main/img/bug.large.png" style="vertical-align: middle;" alt="Comunicar un error" title="Dejar un Mensaje"></a>
            </li>
        </ul>
        <div id="header">
            <div id="header1">
                <div id="top_corner">
                </div>
                <div id="logo">
                            <a href="/"/>
                            <img title="INE Los Pinos - Los Pinos" src="/main/css/tesis/images/header-logo.png" alt="INE Los Pinos - Los Pinos">
                            </a>
                </div>
                    <div id="plugin-header">
                    </div>
                </div>
	<div id="header2">
		<div id="Header2Right">
		<ul>
                    <li>
                    </li>
		</ul>
		</div>
	</div>
	<div id="header4">
	</div>
	<div class="clear">
	</div>
</div>
 
<div id="main">
	<div id="submain">
		<div id="content" class="maincontent">
			<h2>¡Bienvenido asssssssssssssssssssssssssssss!</h2>
			<p>Ahora podrás ver tus cursos y navegar de una forma más sencilla para aprender tus cursos favoritos. Además:<br>
			</p>
			<ol>
				<li>Mira tus cursos</li>
				<li>Conéctate con tus amigos.</li>
				<li>Realiza tus prácticas</li>
			</ol>
			<p>Siempre podrá solicitar más información sobre de el uso de este sistema enviando un correo a: <a href="#">administrador@lospinos.com</a>.</p>
			<p>Diviértete, no dudes en dejarnos tu opinión.</p>
                        
		</div>
		<div id="menu-wrapper">
			<?php echo $this->layout()->content; ?>
		</div>
		<div class="clear">&nbsp;
		</div> <!-- 'clearing' div to make sure that footer stays below the main and right column sections -->
	</div> <!-- end of #main" started at the end of banner.inc.php -->
</div>
<div class="push"></div>
</div><div id="footer">
	<div id="bottom_corner">
	</div>
	<div class="copyright">
		<div align="right">Responsable : 
			<a href="mailto:administrados@lospinos.com" name="clickable_email_link">Tello, Vinces</a>
		</div>
		<div align="right">Plataforma
			<a href="http://www.lospinos.com/" target="_blank">Elearning v. 1.0.0.1</a>© 2011
		</div>
	</div>
	<div class="footer_emails">
		<div id="plugin-footer">
		</div><br>
		<div style="clear:both">
		</div>
	</div>
</div>
<script>
$(document).ready( function() {
    $(".chzn-select").chosen();
});
</script>

</body>
</html>
Inicio de Sesion