<?php    
    $this->titulopagina='Los Pinos - "Descripcion del Curso"';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $urlFoto=$usuario->getFotobyIdUsuario($usuario_id);
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo = $mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $curso = new Application_Model_Cursos();
    $infocurso = $curso->getInfoCurso($this->idcurso);
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="/alumno/cursos" class="breadcrumb breadcrumb0" target="_top">
                    <span>Cursos</span>
                </a>
            </li>
            <li>
                <a href="/alumno/detallecurso?idcurso='.$this->idcurso.'" class="breadcrumb breadcrumb1" target="_top">
                    <span>'.$infocurso[0]['vCursNombreCurso'].'</span>
                </a>
            </li>
            <li>
                <a href="" class="breadcrumb breadcrumb2">
                    <span>Descripcion del Curso</span>
                </a>
            </li>
        </ul>';
    
    $cursos = new Application_Model_Cursos();
    print $html->crearCabecera(null, null, null, $h3, $h4) ;
       
?>

<div id="main">
    <div id="submain">
       <?php
            $detcur = new Application_Model_DetalleCurso();
            switch($this->opt){
                case 'obj':?><h2>Objetivos del Curso</h2><?php
                    break;
                case 'con':?><h2>Contenido del Curso</h2><?php
                    break;
                case 'met':?><h2>Metodología del Curso</h2><?php
                    break;
                case 'mat':?><h2>Materiales para el Curso</h2><?php
                    break;
                case 'rec':?><h2>Recursos Humanos y Técnicos del Curso</h2><?php
                    break;
                case 'eva':?><h2>Evaluación del Curso</h2><?php
                    break;
                case 'nue':?><h2>Apartado Personalizado</h2><?php
                    break;
                    
            }
            
            switch($this->opt){
                case 'ini':
                    ?>
                    <div class="sectiontitle">
                        Objetivos
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "obj");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
        
                    <div class="sectiontitle">
                        Contenidos
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "con");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
        
                    <div class="sectiontitle">
                        Metodología
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "met");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
        
                    <div class="sectiontitle">
                        Materiales
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "mat");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
                    
                    <div class="sectiontitle">
                        Recursos Humanos y Técnicos
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "rec");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
        
                    <div class="sectiontitle">
                        Evaluación
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "eva");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
                <?php    
                    break;
                default:
                    break;
            }
                ?>
    </div>
</div>