<?php
 $this->titulopagina='Los Pinos - "Editar Documentos"';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    $documentos = new Application_Model_Documentos();
    $includes = new Application_Model_Includes();
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $urlFoto=$usuario->getFotobyIdUsuario($usuario_id);
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo = $mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $curso = new Application_Model_Cursos();
    $infocurso = $curso->getInfoCurso($this->idcurso);
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="/alumno/cursos" class="breadcrumb breadcrumb0" target="_top">
                    <span>Cursos</span>
                </a>
            </li>
            <li>
                <a href="/alumno/detallecurso?idcurso='.$this->idcurso.'" class="breadcrumb breadcrumb1" target="_top">
                    <span>'.$infocurso[0]['vCursNombreCurso'].'</span>
                </a>
            </li>
            <li>
                <a href="/alumno/documentos?idcurso='.$this->idcurso.'" class="breadcrumb breadcrumb2">
                    <span>Documentos</span>
                </a>
            </li>
        </ul>';
        
    print $html->crearCabecera(null, null, null, $h3, $h4) ;
    $listadocumentos = $documentos->getDocumentosbyIdCursoIdPadre($this->idcurso, $this->iddocpadre);
?>
<div id="main">
    <div id="submain">
      
        <div><h2>Carpeta Actual: <?php echo $documentos->obternerruta($this->iddocpadre);?></h2></div>
        <table class="data_table">
            <tr class="row_odd">
                <th style="width:30px;">
                    <a href="">Tipo</a>
                </th>
                <th>
                    <a href="">Nombre</a>
                </th>
                <th style="width:50px;">
                    <a href="">Tamaño</a>
                </th>
                <th style="width:105px;">
                    <a href="">Modificado</a>
                </th>
            </tr>
        <?php
        if($listadocumentos==0){
        }
        else{
            foreach($listadocumentos as $documento){
                $iddocumento = $documento['iDocuIdDocumento'];
                ?>
            
            <tr class="row_even">
                <td>
                    <center>
                        <?php
                            if($documento['vDocuTipoDocumento']=="folder"){?>
                        <a href="" title="<?php echo $documento['vDocuTitulo'];?>" target="_self" style="float:left">
                            <img hspace="5" align="middle" height="22" width="22" src="/main/img/folder_document.gif" alt="" title="">
                        </a>
                        <?php
                            }
                            else{
                                ?>
                                <img hspace="5" align="middle" height="22" width="22" src="/main/img/file_txt.gif" alt="" title="">
                            <?php
                            }
                        ?>
                       
                    </center>
                </td>
                <td>
                    <?php
                        if($documento['vDocuTipoDocumento']=="folder"){
                            $href="/alumno/documentos?idcurso=".$this->idcurso."&iddocpadre=".$iddocumento;
                        }
                        else{
                            $href="/".$documento['tDocuRuta'];
                        }
                    ?>
                    <a href="<?php echo $href;?>" title="<?php echo $documento['vDocuTitulo'];?>">
                        <?php echo $documento['vDocuTitulo'];?>
                    </a>
                    <a href="" style="float:right">
                        <img src="/main/img/icons/22/save_pack.png" alt="Descargar" title="Descargar">
                    </a>
                    <br>
                    <i></i>
                </td>
                <td>
                    <center>
                        <?php echo $documento['vDocuTamano'];?>
                    </center>
                </td>
                <td>
                    <center>
                        <a title="<?php 
                        $dia= $includes->timestampToDate($documento['iDocuFechaCreacion']);
                        echo $dia;?>">
                        <?php
                            $segundos_diferencia = time() - $documento['iDocuFechaModificado']; 
                            $dias_diferencia = $segundos_diferencia / (60 * 60 * 24);
                            $dias_diferencia = abs($dias_diferencia);
                            $dias_diferencia = floor($dias_diferencia);
                            if($dias_diferencia<7){
                                if($dias_diferencia==0){
                                    echo "Hoy";
                                }
                                else if($dias_diferencia==1){
                                    echo "Ayer";
                                }
                                else{
                                    echo "Hace ".$dias_diferencia." días";
                                }
                            }
                            else if($dias_diferencia<30){
                                if($dias_diferencia==7){
                                    echo "Hace una semana";
                                }
                                else if($dias_diferencia>=8 && $dias_diferencia<=14){
                                    echo "Hace dos Semanas";
                                }
                                else if($dias_diferencia>14 && $dias_diferencia<15){
                                    echo "Hace tres Semanas";
                                }
                            }
                            else{
                                 if($dias_diferencia==30){
                                    echo "Hace un mes";
                                }
                                else{
                                    echo "Hace ".$dias_diferencia." dias";
                                }
                            }
                        ?>
                        </a>
                    </center>
                </td>
            </tr> 
        
        <?php
            }
        }
        ?>
        </table>
    </div>
</div>