<?php
 $this->titulopagina='Los Pinos - "Lecciones"';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    $documentos = new Application_Model_Documentos();
    $includes = new Application_Model_Includes();
    $cursounidades = new Application_Model_CursoUnidad();
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $script = '
        <script type="text/javascript" src="/main/inc/lib/javascript/jquery-ui/smoothness/jquery-ui-1.8.16.custom.min.js">
        </script>
        ';
    
    $opt = $this->opt;
    
    if(strcmp($opt,"add") == 0){
        
        $unidad=$cursounidades->getunidadCurso($this->idcurunidad);
        
        $diai=strftime("%e",$unidad[0]['dFechaInicio']) + 1;
        $mesi=strftime("%m",$unidad[0]['dFechaInicio']) - 1;
        $anuali=(int)strftime("%Y",$unidad[0]['dFechaInicio']);

        $diaf=strftime("%e",$unidad[0]['dFechaFin']) + 1;
        $mesf=strftime("%m",$unidad[0]['dFechaFin']) - 1;
        $anualf=(int)strftime("%Y",$unidad[0]['dFechaFin']);

        $finicio= $anuali.','.$mesi.','.$diai;
        $ffin= $anualf.','.$mesf.','.$diaf;
        
        $script .= '<script type="text/javascript" src="/js/jquery-ui/jquery-ui-1.8.16.custom.min.js" > </script>
        <script>
        $(function() {
                var dates = $( "#from" ).datepicker({
                        minDate: new Date('.$finicio.'),
                        maxDate: new Date('.$ffin.'),
                        defaultDate: new Date('.$finicio.'),
                        "dateFormat": "mm/dd/yy",    
                        changeMonth: true,
                        numberOfMonths: 1
                });
        });
        </script>';
    }
   
    $css='
        <link rel="stylesheet" href="/main/inc/lib/javascript/jquery-ui/smoothness/jquery-ui-1.8.16.custom.css" type="text/css">
        <link rel="stylesheet" href="/main/inc/lib/javascript/jquery-ui/default.css" type="text/css">';
    $this->script=$script;
    $this->css=$css;
    
    $urlFoto=$usuario->getFotobyIdUsuario($usuario_id);
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo = $mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $curso = new Application_Model_Cursos();
    $infocurso = $curso->getInfoCurso($this->idcurso);
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="/alumno/cursos" class="breadcrumb breadcrumb0" target="_top">
                    <span>Cursos</span>
                </a>
            </li>
            <li>
                <a href="/alumno/detallecurso?idcurso='.$this->idcurso.'" class="breadcrumb breadcrumb1" target="_top">
                    <span>'.$infocurso[0]['vCursNombreCurso'].'</span>
                </a>
            </li>
            <li>
                <a href="/alumno/evaluaciones?idcurso='.$this->idcurso.'&idcurunidad=0" class="breadcrumb breadcrumb2">
                    <span>Evaluaciones</span>
                </a>
            </li>
        </ul>';
        
    print $html->crearCabecera(null, null, null, $h3, $h4) ;
    $cursounidad = new Application_Model_CursoUnidad();
    $listaunidades=$cursounidad->listarCursoUnidad($this->idcurso);
?>
<div id="main">
    <div id="submain">
        <div class="actions">
            <a style="vertical-align: top"><h2>&nbsp;CURSO: <?php echo $infocurso[0]['vCursNombreCurso'];?></h2></a>
            <div class="right">
                <a href="">
                    <img src="/main/img/icons/32/percentage.png" alt="Editar ponderaciones" title="Editar ponderaciones">
                </a>
                <a href="">
                    <img src="/main/img/icons/32/ranking.png" alt="Editar las reglas de puntuación" title="Editar las reglas de puntuación">
                </a>
            </div>
        </div>
        
        <table width="100%" cellpadding="0" cellspacing="0" class="lp_build">
            <tbody>
                <tr style="vertical-align: top;">
                    <td class="tree" width="60px">
                        <div class="lp_tree">
                            <div class="dtree">
                                <?php
                                if(is_array($listaunidades)){
                                foreach($listaunidades as $unidad){
                                    ?>
                                <div class="dTreeNode">
                                    <a href="/alumno/evaluaciones?idcurso=<?php echo $this->idcurso;?>&idcurunidad=<?php echo $unidad['IdCursosUnidades'];?>">
                                        <img id="im0" src="/main/img/icons/22/learnpath.png" alt="">
                                        
                                        <?php echo ($this->idcurunidad==$unidad['IdCursosUnidades']?'<b style="color:red">'.$unidad['vUniDescripcion'].': '.$unidad['vNombreUnidad'].'</b>': $unidad['vUniDescripcion'].': '.$unidad['vNombreUnidad']); ?>
                                    </a>
                                </div>
                                <?php
                                    $evaluaciones = new Application_Model_Evaluaciones();
                                    $listaevaluaciones = $evaluaciones->getEvaluacionesbyIdCursosUnidad($unidad['IdCursosUnidades']);
                                    if(is_array($listaevaluaciones)){
                                        foreach($listaevaluaciones as $evaluacion){
                                            
                                            ?>
                                            <div id="dm0" style="display:block;">
                                                <div class="dTreeNode">
                                                    <img src="/main/img/joinbottom.gif" alt="">
                                                    <img id="im1" src="/main/img/check.gif" alt="">
                                                    <a id="sm1" class="nodeSel" href="evaluaciones?idcurso=<?php echo $this->idcurso;?>&ideval=<?php echo $evaluacion['iEvaIdEvaluacion'];?>">
                                                        <?php echo $evaluacion['iEvaDescripcion'];?>
                                                    </a>
                                                </div>
                                            </div>
                                            <?php
                                        }
                                    }
                                }
                                }
                                ?>
                            </div>
                        </div>
                    </td>
                    <td class="workspace">
                        <?php
                        if ($this->idcurunidad==0){
                        ?>
                        <div class="normal-message" style="margin-left: 20px">
                            <h2>Evaluaciones Pendientes</h2>
                        </div>
                            <?php
                                $listaevaluacionespendientes = $evaluaciones->getEvaluacionesPendientes($this->idcurso);
                                if(is_array($listaevaluacionespendientes)){
                                        foreach($listaevaluacionespendientes as $evaluacion){
                                            $nropreguntas = $evaluaciones->getPreguntasxEvaluacion($evaluacion['iEvaIdEvaluacion']);
                                            if(is_array($nropreguntas)){
                                                $nropreguntas=sizeof($nropreguntas);
                                            }
                                                ?>
                        <div class="normal-message" style="margin-left: 40px; margin-right: 20px">
                            <span style="display: inline; text-align: center">
                                <h1><?php echo $evaluacion['iEvaDescripcion'];?></h1>
                            </span>
                            <span style="display: block; text-align: center">
                                <img src="/main/img/blackboard.png">
                            </span>
                            <span style="display: inline; text-align: center">
                                <h3>Nro Preguntas : <?php echo $nropreguntas;?></h3>
                                <h3>Puntaje Mínimo Aprobatorio: <?php echo $evaluacion['iEvaPuntMin'];?></h3>
                            </span>
                            <span style="display: inline; text-align: center">
                                <form action="/alumno/rendirevaluacion?idcurso=<?php echo $this->idcurso;?>&ideval=<?php echo $evaluacion['iEvaIdEvaluacion'];?>&opt=add" method="post">
                                    <button class="plus" type="submit">
                                        Rendir Examen
                                    </button>
                                </form>
                            </span>
                        </div>
                                            <?php
                                            }
                                }
                            ?>
                        <?php
                        }
                        else{
                            $curunidad = $cursounidad->getunidadCurso($this->idcurunidad);
                        ?>
                            <div class="normal-message"  style="margin-left: 15px">
                                <h2>Unidad: <?php echo $curunidad[0]['vNombreUnidad'];?></h2>
                                <?php
                                    if(strcmp($this->ideval,"0")!=0){
                                        //$infoleccion = $lecciones->getLeccionbyIdLeccion($this->idleccion);
                                        ?>
                                    <div class="actions" style="background: white; padding: 0 10px 0 10px">
                                            <p>
                                                sssss
                                            </p>
                                    </div>
                                        <?php
                                    }
                                    else if(strcmp($this->opt,"add")!=0){
                                        ?>
                                        <table class="data_table">
                                                    <tbody>
                                                        <tr class="row_odd">
                                                            <th>Nombre</th>
                                                            <th>Nota Mínima</th>
                                                            <th>Mi Nota</th>
                                                            <th width="100px">Fecha de Creacion</th>
                                                            <th width="100px">Fecha de Evaluación</th>
                                                            <th width="auto">Acción</th>
                                                        </tr>
                                        <?php
                                        $evaluaciones = new Application_Model_Evaluaciones();
                                        $listaevaluaciones = $evaluaciones->getEvaluacionesbyIdCursosUnidad($this->idcurunidad);
                                        if(is_array($listaevaluaciones)){
                                            foreach($listaevaluaciones as $evaluacion){
                                                
                                                ?>
                                                        <tr class="row_even">
                                                            <td>
                                                                <center>
                                                                    <?php echo $evaluacion['iEvaDescripcion'];?>
                                                                </center>
                                                            </td>
                                                            <td>
                                                                <center>
                                                                    <?php echo $evaluacion['iEvaPuntMin'];?>
                                                                </center>
                                                            </td>
                                                            <td>
                                                                <center>
                                                                    <?php echo $evaluacion['iEvaPuntMin'];?>
                                                                </center>
                                                            </td>
                                                            <td>
                                                                <center>
                                                                    <?php
                                                                        $fecha = $includes->timestampToDate($evaluacion['iEvaFechaCreacion']);
                                                                        echo $fecha;
                                                                    ?>
                                                                </center>
                                                            </td>
                                                            <td>
                                                                <center>
                                                                    <?php
                                                                        $fecha = $includes->timestampToDate($evaluacion['iEvaFechaExamen']);
                                                                        echo $fecha;
                                                                    ?>
                                                                </center>
                                                            </td>
                                                            <td>
                                                                <center>
                                                                    <?php
                                                                        if($evaluacion['iEvaFechaExamen']<time()){
                                                                    ?>
                                                                    <a href="">
                                                                        <img src="/main/img/icons/22/visible.png" alt="Ver" title="Ver">
                                                                    </a>
                                                                    <?php
                                                                        }
                                                                        else
                                                                        {
                                                                    ?>
                                                                    <img src="/main/img/icons/22/invisible.png" alt="Ver" title="Ver">    
                                                                    <?php
                                                                        }    
                                                                    ?>
                                                                </center>
                                                            </td>
                                                        </tr>
                                                <?php
                                            }
                                        }
                                        ?>
                                                    </tbody>
                                                </table>
                                        <?php
                                    }
                                    
                                    if(strcmp($this->opt,"add")==0){
                                        ?>
                                <form action="/alumno/agregarevaluacion?idcurso=<?php echo $this->idcurso;?>&idcurunidad=<?php echo $this->idcurunidad;?>&opt=add" method="post">
                                    <p>
                                    <table>
                                        <tr>
                                            <td>
                                                Titulo de la Evaluación:
                                            </td>
                                            <td>
                                                <input type="text" name="txttitulo"/>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Nota Mínima Aprobatoria:
                                            </td>
                                            <td>
                                                <input type="text" name="txtnotamin" size="7">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Fecha de Examen: 
                                            </td>
                                            <td colspan="2">
                                                <input size="12" name="fechaex" id="from" type="text">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <button class="add" name="submit" type="submit">Grabar</button>
                                            </td>
                                        </tr>
                                    </table>
                                    </p>
                                </form>
                                        <?php
                                    }
                                ?>
                                
                            </div>
                        <?php
                        }
                        ?>
                    </td>
                </tr>
            </tbody>
        </table>
        
        <div class="clear">&nbsp;
        </div>
    </div>
</div>