<?php
    include_once "ckeditor/ckeditor.php";
    
    $this->titulopagina='Los Pinos - "Descripcion del Curso"';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $urlFoto=$usuario->getFotobyIdUsuario($usuario_id);
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo = $mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $curso = new Application_Model_Cursos();
    $infocurso = $curso->getInfoCurso($this->idcurso);
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="/docente/cursos" class="breadcrumb breadcrumb0" target="_top">
                    <span>Cursos</span>
                </a>
            </li>
            <li>
                <a href="/docente/detallecurso?idcurso='.$this->idcurso.'" class="breadcrumb breadcrumb1" target="_top">
                    <span>'.$infocurso[0]['vCursNombreCurso'].'</span>
                </a>
            </li>
            <li>
                <a href="" class="breadcrumb breadcrumb2">
                    <span>Descripcion del Curso</span>
                </a>
            </li>
        </ul>';
    
    $cursos = new Application_Model_Cursos();
    print $html->crearCabecera(null, null, null, $h3, $h4) ;
       
?>

<div id="main">
    <div id="submain">
        <div class="actions" style="margin-bottom:30px">
            <a href="?idcurso=<?php echo $this->idcurso;?>&opt=ini">
                <img src="/main/img/icons/32/info.png" alt="Descripción general" title="Descripción general">
            </a>
            <a href="?idcurso=<?php echo $this->idcurso;?>&opt=obj">
                <img src="/main/img/icons/32/objective.png" alt="Objetivos" title="Objetivos">
            </a>
            <a href="?idcurso=<?php echo $this->idcurso;?>&opt=con">
                <img src="/main/img/icons/32/topics.png" alt="Contenidos" title="Contenidos">
            </a>
            <a href="?idcurso=<?php echo $this->idcurso;?>&opt=met">
                <img src="/main/img/icons/32/strategy.png" alt="Metodología" title="Metodología">
            </a>
            <a href="?idcurso=<?php echo $this->idcurso;?>&opt=mat">
                <img src="/main/img/icons/32/laptop.png" alt="Materiales" title="Materiales">
            </a>
            <a href="?idcurso=<?php echo $this->idcurso;?>&opt=rec">
                <img src="/main/img/icons/32/teacher.png" alt="Recursos humanos y técnicos" title="Recursos humanos y técnicos">
            </a>
            <a href="?idcurso=<?php echo $this->idcurso;?>&opt=eva">
                <img src="/main/img/icons/32/assessment.png" alt="Evaluación" title="Evaluación">
            </a>
            <a href="?idcurso=<?php echo $this->idcurso;?>&opt=nue">
                <img src="/main/img/icons/32/wizard.png" alt="Apartado personalizado" title="Apartado personalizado">
            </a>
     </div>
       <?php
            $detcur = new Application_Model_DetalleCurso();
            switch($this->opt){
                case 'obj':?><h2>Objetivos del Curso</h2><?php
                    break;
                case 'con':?><h2>Contenido del Curso</h2><?php
                    break;
                case 'met':?><h2>Metodología del Curso</h2><?php
                    break;
                case 'mat':?><h2>Materiales para el Curso</h2><?php
                    break;
                case 'rec':?><h2>Recursos Humanos y Técnicos del Curso</h2><?php
                    break;
                case 'eva':?><h2>Evaluación del Curso</h2><?php
                    break;
                case 'nue':?><h2>Apartado Personalizado</h2><?php
                    break;
                    
            }
            
            switch($this->opt){
                case 'ini':
                    ?>
                    <div class="sectiontitle">
                        <a href="?idcurso=<?php echo $this->idcurso;?>&opt=obj">
                            <img style="vertical-align:middle;float:right; padding-right:4px;" src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
                        </a>Objetivos
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "obj");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
        
                    <div class="sectiontitle">
                        <a href="?idcurso=<?php echo $this->idcurso;?>&opt=con">
                            <img style="vertical-align:middle;float:right; padding-right:4px;" src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
                        </a>Contenidos
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "con");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
        
                    <div class="sectiontitle">
                        <a href="?idcurso=<?php echo $this->idcurso;?>&opt=met">
                            <img style="vertical-align:middle;float:right; padding-right:4px;" src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
                        </a>Metodología
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "met");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
        
                    <div class="sectiontitle">
                        <a href="?idcurso=<?php echo $this->idcurso;?>&opt=mat">
                            <img style="vertical-align:middle;float:right; padding-right:4px;" src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
                        </a>Materiales
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "mat");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
                    
                    <div class="sectiontitle">
                        <a href="?idcurso=<?php echo $this->idcurso;?>&opt=rec">
                            <img style="vertical-align:middle;float:right; padding-right:4px;" src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
                        </a>Recursos Humanos y Técnicos
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "rec");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
        
                    <div class="sectiontitle">
                        <a href="?idcurso=<?php echo $this->idcurso;?>&opt=eva">
                            <img style="vertical-align:middle;float:right; padding-right:4px;" src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
                        </a>Evaluación
                    </div>
                    <div class="sectioncomment">
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, "eva");
                            print html_entity_decode($result==0? "Aun no se ha editado": $result[0]['tValor']);
                        ?>                        
                    </div>
                <?php    
                    break;
                case 'obj':
                case 'con':
                case 'met':
                case 'mat':
                case 'rec':
                case 'eva':
                case 'nue':     
                    ?>
                     
                    
                    <form action="/docente/agregardetallecurso?idcurso=<?php echo $this->idcurso;?>&opt=<?php echo $this->opt;?>" method="post">
                        <p>
                        <?php
                            $result = $detcur->getDetalle($this->idcurso, $this->opt);
                            $initialValue = ($result==0? "" : html_entity_decode($result[0]['tValor']));
                            $CKEditor = new CKEditor();
                            $CKEditor->basePath = '/ckeditor/';
                            $CKEditor->editor("editor1", ''.$initialValue);
                        ?>
                            <input type="submit" value="Submit"/>
                        </p>
                    </form>
                    <?php    
                    break;
                case 'con':
                    break;
                default:
                    break;
            }
                ?>
    </div>
</div>