<?php    
    $this->titulopagina='Los Pinos - "Editar Unidades"';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $urlFoto=$usuario->getFotobyIdUsuario($usuario_id);
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo = $mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $curso = new Application_Model_Cursos();
    $infocurso = $curso->getInfoCurso($this->idcurso);
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="/docente/cursos" class="breadcrumb breadcrumb0" target="_top">
                    <span>Cursos</span>
                </a>
            </li>
            <li>
                <a href="/docente/detallecurso?idcurso='.$this->idcurso.'" class="breadcrumb breadcrumb1" target="_top">
                    <span>'.$infocurso[0]['vCursNombreCurso'].'</span>
                </a>
            </li>
            <li>
                <a href="/docente/editarunidades?idcurso='.$this->idcurso.'" class="breadcrumb breadcrumb2">
                    <span>Editar Unidades</span>
                </a>
            </li>
        </ul>';
        
    //print $html->crearWrapper(null, null, null, $h3, $h4 ,null, null,$content);
    print $html->crearCabecera(null, null, null, $h3, $h4) ;
    $cursounidad = new Application_Model_CursoUnidad();
    $listaunidades=$cursounidad->listarCursoUnidad($this->idcurso);
?>
<div id="main">
    <div id="submain">
        <div class="centraTabla">
            <table class="data_table" style="width:80%;">
                <tbody>
                    <tr class="row_odd">
                        <th><a href="">Nro. Unidad</a></th>
                        <th><a href="">UNIDAD</a></th>
                        <th><a href="">TITULO DE LA UNIDAD</a></th>
                        <th><a href="">Opciones</a></th>
                    </tr>
                    <?php
                    foreach($listaunidades as $unidad){
                        ?>

                    <tr class="row_even">
                        <td>
                            <center><?php echo $unidad['iNroUnidad']; ?></center>
                        </td>
                        
                        <td>
                            <center><?php echo $unidad['vUniDescripcion']; ?></center>
                        </td>
                        <td>
                            <center><?php echo $unidad['vNombreUnidad']; ?></center>
                        </td>
                        <td>
                            <center>
                                <a href="verunidadcurso?idcur=<?php echo $this->idcurso; ?>&idunicur=<?php echo $unidad['IdCursosUnidades']; ?>">
                                    <img src="/main/img/icons/22/scorms.png" alt="Ver" title="Ver">
                                </a>
                                <a href="editarunidadcurso?idcur=<?php echo $this->idcurso; ?>&idunicur=<?php echo $unidad['IdCursosUnidades']; ?>">
                                    <img src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
                                </a>
                            </center>
                        </td>
                    </tr>
                    <?php
                    }
                    ?>                
                </tbody>
            </table>
        </div>
    </div>
</div>