<?php
 $this->titulopagina='Los Pinos - "Glosario"';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    $documentos = new Application_Model_Documentos();
    $includes = new Application_Model_Includes();
    $cursounidades = new Application_Model_CursoUnidad();
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $script = '
        <script type="text/javascript" src="/main/inc/lib/javascript/jquery-ui/smoothness/jquery-ui-1.8.16.custom.min.js">
        </script>
        ';
    
    $css='
        <link rel="stylesheet" href="/main/inc/lib/javascript/jquery-ui/smoothness/jquery-ui-1.8.16.custom.css" type="text/css">
        <link rel="stylesheet" href="/main/inc/lib/javascript/jquery-ui/default.css" type="text/css">';
    $this->script=$script;
    $this->css=$css;
    
    $urlFoto=$usuario->getFotobyIdUsuario($usuario_id);
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo = $mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $curso = new Application_Model_Cursos();
    $infocurso = $curso->getInfoCurso($this->idcurso);
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="/docente/cursos" class="breadcrumb breadcrumb0" target="_top">
                    <span>Cursos</span>
                </a>
            </li>
            <li>
                <a href="/docente/detallecurso?idcurso='.$this->idcurso.'" class="breadcrumb breadcrumb1" target="_top">
                    <span>'.$infocurso[0]['vCursNombreCurso'].'</span>
                </a>
            </li>
            <li>
                <a href="/docente/glosario?idcurso='.$this->idcurso.'" class="breadcrumb breadcrumb2">
                    <span>Glosario</span>
                </a>
            </li>
        </ul>';
        
    print $html->crearCabecera(null, null, null, $h3, $h4) ;
    $glosario = new Application_Model_Glosario();
    $listaterminos=$glosario->getGlosarioCursobyIdCurso($this->idcurso);
?>
<div id="main">
    <div id="submain">
        
        <?php
            if(strcmp($this->opt, "add")==0){
                ?>
                <form action="/docente/editartermino?idcurso=<?php echo $this->idcurso;?>&opt=add" method="post">
                    <div class="row">
                        <div class="form_header">
                            Nuevo Término
                        </div>
                    </div>
                    <div class="row">
                        <div class="label">
                            <span class="form_required">*</span>Nombre del Término
                        </div>
                        <div class="formw">
                            &nbsp;&nbsp;&nbsp;<input type="text" name="txttermino">
                        </div>
                    </div>
                    <div class="row">
                        <div class="label">
                            <span class="form_required">*</span>Definición
                        </div>
                        <div class="formw">
                            &nbsp;&nbsp;&nbsp;<input type="text" name="txtdefinicion">
                        </div>
                    </div>
                    <div class="row">
                        <div class="label">&nbsp;</div>
                        <div class="formw">
                            <button type="submit" class="add">Añadir término</button>
                        </div>
                    </div>
                </form>
                <?php
            }
            else{?>
                <div class="actions" style="margin-bottom:10px">
            <a href="/docente/glosario?idcurso=<?php echo $this->idcurso;?>&opt=add">
                <img src="/main/img/icons/32/new_glossary_term.png" alt="Añadir un término" title="Añadir un término"> Añadir un término
            </a>            
        </div>
            <?php
            }
       ?>        
        <table class="data_table">
            <tbody>
                <tr class="row_odd">
                    <th>
                        <a href="">
                            Término</a>
                    </th>
                    <th>
                        <a href="">
                            Definición
                        </a>
                    </th>
                    <th>
                        Opciones
                    </th>
                </tr>
                <?php
                 if(is_array($listaterminos)){
                     foreach($listaterminos as $termino){
                         ?>
                         <tr class="row_even">
                            <td>
                                <center><?php echo $termino['vGlosTermino'];?></center>
                            </td>
                            <td>
                                <center><?php echo $termino['tGlosDefinicion'];?></center>
                            </td>
                            <td>
                                <center>
                                    <a href="">
                                        <img src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
                                    </a>
                                    <a href="" >
                                        <img src="/main/img/icons/22/delete.png" alt="Eliminar" title="Eliminar">
                                    </a>
                                </center>
                            </td>
                        </tr>
                         <?php
                     }
                 }
                 else{
                     ?>
                <tr class="row_even">
                    <td colspan="3">
                        <center>
                            Aún no se han registrado términos.
                        </center>
                    </td>
                </tr>
                <?php
                 }
                ?>
                
            </tbody>
        </table>
    </div>
</div>