<?php
    $html= new Application_Model_Html();
    //$html->setLayoutt($this);
    print $html->crearDoctype();
    print $html->cargarCss($this->css);
    print $html->cargarScript($this->script);
    print $html->setTitle($this->titulopagina);
    print $html->closeHead();
    print '<body>';
?>
<?php
    if (Zend_Session::sessionExists()){
        print $this->layout()->content.'
            </body>
            </html>';
    }
    else {
        $head2='<div id="Header2Right">
                        <ul>
                            <li>
                            </li>
                            <li>
                                <a href="" target="_top" title="Usuarios en línea">
                                    <img width="13px" src="/main/img/members.gif" title="Usuarios en línea"> 2
                                </a>
                            </li>
                        </ul>
                    </div>';
        $content='
                 <h1 style="color: #4A6AA4">¡Bienvenido al portal Educativo de Los Pinos!</h1>
                    <br/>
                    <table>
                        <tr>
                            <td width="80%">
                                <img align="center" src="/main/img/portada.jpg" width="90%" /></td>
                            <td>
                                <p>Ahora podrás ver tus cursos y navegar de una forma más sencilla para aprender tus cursos favoritos. Además:<br>
                                </p>
                                <ol>
                                    <li>Mira tus cursos</li>
                                    <li>Conéctate con tus amigos.</li>
                                    <li>Realiza tus prácticas</li>
                                </ol>
                                <p>Siempre podrá solicitar más información sobre de el uso de este sistema enviando un correo a: <a href="#">administrador@lospinos.com</a>.</p>
                                <p>Diviértete, no dudes en dejarnos tu opinión.</p>  
                            </td>
                        </tr>
                    </table>';
        
        print $html->crearWrapper(null, null, $head2, null, null, $content, $this->layout()->content,null);
    }
    print $html->crearFooter();
     
?>

