<?php
    $this->titulopagina='Aula Virtual "LOS PINOS"';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id; 
    
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/apoderado/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="principal" class="breadcrumb breadcrumb0" target="_top">
                    <span>Mi Página Principal</span>
                </a>
            </li>
        </ul>';
    $contenido = 'Bienvenido Usuario';
    $submain='
        <div id="menu-wrapper">
            <div id="menu" class="menu">
                <div class="menusection  ">
                    <span class="menusectioncaption">Perfil</span>
                    <div id="social_widget">
                        <div id="social_widget_image">
                            <a href="">
                                <img title="Editar perfil" src="/main/img/unknown.jpg" width="90" height="90" border="1">
                            </a>
                        </div>
                    </div>
                <div class="clear">
                </div>
                <div class="message-content">
                    <ul class="menulist">
                        <li>
                            <a href="" class="message-body">Bandeja de entrada </a>
                        </li>
                        <li>
                            <a href="" class="message-body">Redactar </a>
                        </li>
                        <li>
                            <a href="" class="message-body">Invitaciones pendientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="menu" id="menu">
            <div class="menusection">
                <span class="menusectioncaption">Usuario</span>
                    <ul class="menulist">
                        <li>
                            <a href="">Crear un curso</a>
                        </li>
                        <li>
                            <a href="">Catálogo de cursos</a>
                        </li>
                    </ul>
             </div>
         </div>
         <div id="menu" class="menu">
            <div class="menusection  ">
                <span class="menusectioncaption">General</span>
                    <ul class="menulist">
                        <li>
                            <a href="" target="_self">Forum</a>
                        </li>
                    </ul>
            </div>
         </div>
         </div>
        ';
    
    print $html->crearCabecera(null, null, null, $h3, $h4);
    $apoderado = new Application_Model_Apoderado();
    $idapoderado = $apoderado->getApoderadobyIdUsuario($usuario_id);
    $alumnos = new Application_Model_Alumno();
    $listaalumnos = $alumnos->getAlumnosbyIdApoderado($idapoderado[0]['iApodIdApoderado']);
?>
<div id="main">
    <div id="submain">
        <div class="maincontent" id="content">
            <h1>
                <img title="Estudiantes a Cargo" alt="Estudiantes a Cargo" src="/main/img/icons/22/user.png"> Estudiantes a Cargo
            </h1>
            <div id="plugin-mycourses_main">
            </div>
            <?php
                foreach($listaalumnos as $alumno){
                 $seccion = new Application_Model_Seccion();
                 $datosseccion = $seccion->getSeccionbyIdSeccion($alumno['Seccion_iSeccIdSeccion']);
                 ?>
             <div class="userportal-course-item">
                <div style="float: left; margin-right: 10px;">
                    <a href="">
                        <img height="40px" width="40px" title="Curso" alt="Curso" src="/<?php echo $alumno['tFoto'];?>">
                    </a>
                </div>
                <span class="userportal-course-item-title">
                    <a href="">
                        <?php echo $alumno['vUsuApellidoPat'].' '.$alumno['vUsuApellidoMat'].', '.$alumno['vUsuNombre'];?>
                    </a>
                </span><br>Grado: <a style="color:#5084A0;"><?php echo $datosseccion[0]['vGradoDescripcion'].' '.$datosseccion[0]['vSeccDescripcion'];?></a>&nbsp;
            </div>
                    <?php
                }
            ?>
           
        </div>
        <div id="menu-wrapper">
            <div class="menu" id="menu">
                <div class="menusection  ">
                    <span class="menusectioncaption">Perfil</span>
                    <div id="social_widget">
                        <div id="social_widget_image">
                            <a href="">
                                <img width="90" height="90" border="1" src="/main/img/unknown.jpg" title="Editar perfil">
                            </a>
                        </div>
                    </div>
                    <div class="clear">
                    </div>
                    <div class="message-content">
                        <ul class="menulist">
                            <li>
                                <a class="message-body" href="">Bandeja de entrada </a>
                            </li>
                            <li>
                                <a class="message-body" href="">Redactar </a>
                            </li>
                            <li>
                                <a class="message-body" href="">Contactar</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>