<?php
    $this->titulopagina='Los Pinos - Aperturar Cursos';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $h3 = '<ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='
        <ul class="bread">
            <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="panel" class="breadcrumb breadcrumb0" target="_top">
                    <span>Panel de Control</span>
                </a>
            </li>
            <li>
                <a href="aperturarcursos" class="breadcrumb breadcrumb1">
                    <span>Aperturar Cursos</span>
                </a>
            </li>
        </ul>';
           
        $contenido = '
            <div id="submain">
                <div class="actions" style="margin-bottom:30px">
                    <select name="action">
                        <option value="0">Selecionar Grado</option>';
                    
        $grados=new Application_Model_Grado();
        $listagrados=$grados->listarGradosActivos();
            foreach($listagrados as $aux){
                $contenido.='<option value="'.$aux['iGradoIdGrado'].'">'.$aux['vGradoDescripcion'].'</option>';
            }
                    $contenido .= '
                    </select>
                </div><form method="post" action="" name="form_attendance_list">
                <table class="data_table">
                    <tbody>
                        <tr class="row_odd">
                            <th style="width:20px;">&nbsp;</th>
                            <th><a>Nombre</a></th>
                            <th><a>Descripción</a></th>
                            <th style="width:90px;"><a>Asistencias</a></th>
                            <th style="text-align:center">Opciones</th>
                        </tr>
                        <tr class="row_even">
                            <td><input type="checkbox" name="id[]" value="1"></td>
                            <td><a href="">1er Trimestre</a></td>
                            <td>-</td>
                            <td><center>0</center></td>
                            <td><center><a href=""><img src="/main/img/icons/22/edit.png" alt="Editar" title="Editar"></a>&nbsp;<a onclick=""><img src="/main/img/icons/22/delete.png" alt="Eliminar" title="Eliminar"></a></center></td>
                        </tr>
                    </tbody>
                </table>
                <table style="width:100%;">
                    <tbody>
                        <tr>
                            <td colspan="2"><br>
                                <button type="submit" class="save">
                                    Guardar
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
                </form>
                <div class="clear">&nbsp;</div>
            </div>';
    
    print $html->crearWrapper(null, null, null, $h3, $h4 ,$this->layout()->content, null,$contenido);
?>