<?php
    $this->titulopagina='Los Pinos - "Cursos"';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="cursos" class="breadcrumb breadcrumb0" target="_top">
                    <span>Cursos</span>
                </a>
            </li>
        </ul>';
    $contenido = '
        <div class="admin_section">
            <h4><img src="/main/img/course.gif" alt="Cursos" title="Cursos"> Cursos</h4>
            <ul>
                <li><a href="nuevocurso?page=1&nroreg=6">Crear un curso</a></li>                
                <li><a href="listacursos?page=1&nroreg=6">Lista de cursos</a></li>
                <li><a href="asignardocentecurso">Asignar Docentes</a></li>
                <li><a href="subscribe_user2course.php">Inscribir usuarios en un curso</a></li>
            </ul>
        </div>
        <div class="admin_section">
           <h4><img src="/main/img/course.gif" alt="Secciones" title="Secciones"> Secciones</h4>
           <ul>
                <li><a href="course_list.php">Lista de Secciones</a></li>
                <li><a href="course_add.php">Crear una Seccion</a></li>
                <li><a href="course_category.php">Secciones por Grado</a></li>
            </ul>
        </div>
        ';
    
    print $html->crearWrapper(null, null, null, $h3, $h4 ,null, null,$contenido);
?>

