<?php
$html= new Application_Model_Html();
$contenido='
<h4>Lista de Secciones</h4>
<table class="data_table">
<tbody>
<tr class="row_odd">
<th width="18px">&nbsp;</th>
<th>Codigo</th>
<th><a href="">Grado</a></th>
<th><a href="">Sección</a></th>
<th width="15px"><a href="">Activo</a></th>
<th width="220px">Acción</th>
</tr>';
        
        $seccion = new Application_Model_Seccion();
        $listasecciones = $seccion->listarSeccionesPeriodoActual();
        
        $cont=0;
        foreach ($listasecciones as $aux){
            if ($cont % 2){
                $contenido.='<tr class="row_even">';
            }
            else{
                $contenido .= '<tr class="row_odd">';
            }
            $contenido.='
<td>
<input type="checkbox" name="id[]" value="4">
</td>
<td>
<center>'.$aux['iSeccIdSeccion'].'</center>
</td>

<td>
<center>'.$aux['vGradoDescripcion'].'</center>
</td>
<td>
<center>'.$aux['vSeccDescripcion'].'</center>
</td>
<td>
<center>';
                            if($aux['tiSeccEstado']=='A'){
                               $contenido.='<a class="actsecc" onclick="ActDelSeccion('.$aux['iSeccIdSeccion'].',\'I\',event,\'act\');" href="/admin/actualizarseccion/?secc='.$aux['iSeccIdSeccion'].'&est=I" ><img id="img_4" src="/main/img/icons/16/accept.png" alt="Desactivar" title="Desactivar"></a>';
                            }
                            else{
                              $contenido.='<a class="actsecc" onclick="ActDelSeccion('.$aux['iSeccIdSeccion'].',\'A\',event,\'act\');" href="/admin/actualizarseccion/?secc='.$aux['iSeccIdSeccion'].'&est=A" ><img id="img_4" src="/main/img/icons/16/error.png" alt="Activar" title="Activar"></a>';
                            }
            $contenido.='
</center>
</td>
<td>
<a href="">
<img src="/main/img/course.gif" title="Cursos" alt="Cursos" />
</a>&nbsp;&nbsp;
<a href="">
<img src="/main/img/synthese_view.gif" alt="Información" title="Información">
</a>&nbsp;&nbsp;
<a href="">
<img src="/main/img/login_as.gif" alt="Iniciar sesión como" title="Iniciar sesión como">
</a>&nbsp;&nbsp;
<img src="/main/img/statistics_na.gif" alt="Informes" title="Informes">&nbsp;&nbsp;
<a href="">
<img src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
</a>&nbsp;
<img src="/main/img/admin_star_na.png" alt="No es administrador" title="No es administrador" />';
                            
                            if ($cont<sizeof($listasecciones)-1){
                                if($aux['vGradoDescripcion']==$listasecciones[$cont+1]['vGradoDescripcion']){
                                    $contenido.='
<a>
<img src="/main/img/icons/22/delete_na.png" alt="No Eliminar" title="No Puede Eliminarse">
</a>';
                                }
                                else{
                                    $contenido.='
<a onclick="ActDelSeccion('.$aux['iSeccIdSeccion'].',\'nad\',event,\'del\');" href="/admin/eliminarseccion/?secc='.$aux['iSeccIdSeccion'].'">
<img src="/main/img/icons/22/delete.png" alt="Eliminar?" title="Eliminar?">
</a>';
                                }
                            }
                            else {
                                $contenido.='
<a onclick="ActDelSeccion('.$aux['iSeccIdSeccion'].',\'nad\',event,\'del\');" href="/admin/eliminarseccion/?secc='.$aux['iSeccIdSeccion'].'">
<img src="/main/img/icons/22/delete.png" alt="Eliminar?" title="Eliminar?">
</a>';
                            }
                                    
                       $contenido.='
</td>
</tr>';
            
            $cont++;
        }
        
$contenido .= '</tbody>
</table>';
        print $html->crearContentAjax($contenido);
   //print $html->crearWrapperSubmainAjax($contenido);
?>