<?php
    $this->titulopagina='Los Pinos - Lista de Usuarios';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $h3 = '<ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='
        <ul class="bread">
            <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="usuarios" class="breadcrumb breadcrumb0" target="_top">
                    <span>Usuarios</span>
                </a>
            </li>
            <li>
                <a href="listausuarios" class="breadcrumb breadcrumb1">
                    <span>Lista de Usuarios</span>
                </a>
            </li>
        </ul>';
           
        $contenido = '
            <table class="data_table">
	<tbody>
        <tr class="row_odd">
		<th width="18px">&nbsp;</th>
		<th>Foto</th>
		<th><a href="">DNI</a> ↑</th>
		<th><a href="">Apellidos</a></th>
		<th><a href="">Nombre</a></th>
		<th><a href="">Usuario</a></th>
		<th><a href="">Correo electrónico</a></th>
		<th><a href="">Perfil</a></th>
		<th width="15px"><a href="">Activo</a></th>
		<th width="220px">Acción</th>
	</tr>
	<tr class="row_even">
            <td>
                <input type="checkbox" name="id[]" value="4">
            </td>
            <td>
                <center>
                    <a href="http://localhost:3001/chamilo/whoisonline.php?origin=user_list&amp;id=4" title="Información">
                        <img src="/main/img/unknown.jpg" width="22" height="22" alt="Josesito, Vinces Ortiz" title="Josesito, Vinces Ortiz">
                    </a>
                </center>
            </td>
            <td>
                <center>666</center>
            </td>
            <td>
                <center>
                    <a href="http://localhost:3001/chamilo/whoisonline.php?origin=user_list&amp;id=4">Vinces Ortiz</a>
                </center>
            </td>
            <td>
                <center>
                    <a href="http://localhost:3001/chamilo/whoisonline.php?origin=user_list&amp;id=4">Josesito</a>
                </center>
            </td>
            <td>
                <center>jvinceso</center>
            </td>
            <td>
                <center>
                    <a href="mailto:jvinceso@gilmail.com" name="clickable_email_link">jvinceso@gilmail.com</a>
                </center>
            </td>
            <td>
                <center>Profesor</center>
            </td>
            <td>
                <center>
                    <img onclick="active_user(this);" id="img_4" src="/main/img/icons/16/accept.png" alt="Bloquear" title="Bloquear">
               </center>
            </td>
            <td>
                <a href="">
                    <img src="/main/img/course.gif" title="Cursos" alt="Cursos" />
                </a>&nbsp;&nbsp;
                <a href="">
                    <img src="/main/img/synthese_view.gif" alt="Información" title="Información">
                </a>&nbsp;&nbsp;
                <a href="">
                    <img src="/main/img/login_as.gif" alt="Iniciar sesión como" title="Iniciar sesión como">
                </a>&nbsp;&nbsp;
                <img src="/main/img/statistics_na.gif" alt="Informes" title="Informes">&nbsp;&nbsp;
                <a href="">
                    <img src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
                </a>&nbsp;
                <img src="/main/img/admin_star_na.png" alt="No es administrador" title="No es administrador" />
                <a class="agenda_opener">
                    <img src="/main/img/icons/22/month.png" alt="Calendario libre/ocupado" title="Calendario libre/ocupado">
                </a>
            </td>
	</tr>
	<tr class="row_odd">
            <td>
                <input type="checkbox" name="id[]" value="4">
            </td>
            <td>
                <center>
                    <a href="http://localhost:3001/chamilo/whoisonline.php?origin=user_list&amp;id=4" title="Información">
                        <img src="/main/img/unknown.jpg" width="22" height="22" alt="Josesito, Vinces Ortiz" title="Josesito, Vinces Ortiz">
                    </a>
                </center>
            </td>
            <td>
                <center>666</center>
            </td>
            <td>
                <center>
                    <a href="http://localhost:3001/chamilo/whoisonline.php?origin=user_list&amp;id=4">Vinces Ortiz</a>
                </center>
            </td>
            <td>
                <center>
                    <a href="http://localhost:3001/chamilo/whoisonline.php?origin=user_list&amp;id=4">Josesito</a>
                </center>
            </td>
            <td>
                <center>jvinceso</center>
            </td>
            <td>
                <center>
                    <a href="mailto:jvinceso@gilmail.com" name="clickable_email_link">jvinceso@gilmail.com</a>
                </center>
            </td>
            <td>
                <center>Profesor</center>
            </td>
            <td>
                <center>
                    <img onclick="active_user(this);" id="img_4" src="/main/img/icons/16/accept.png" alt="Bloquear" title="Bloquear">
               </center>
            </td>
            <td>
                <a href="javascript:void(0)">
                    <img src="/main/img/course.gif" title="Cursos" alt="Cursos" />
                </a>&nbsp;&nbsp;
                <a href="user_information.php?user_id=4">
                    <img src="/main/img/synthese_view.gif" alt="Información" title="Información">
                </a>&nbsp;&nbsp;
                <a href="">
                    <img src="/main/img/login_as.gif" alt="Iniciar sesión como" title="Iniciar sesión como">
                </a>&nbsp;&nbsp;
                <img src="/main/img/statistics_na.gif" alt="Informes" title="Informes">&nbsp;&nbsp;
                <a href="user_edit.php?user_id=4">
                    <img src="/main/img/icons/22/edit.png" alt="Editar" title="Editar">
                </a>&nbsp;
                <img src="/main/img/admin_star_na.png" alt="No es administrador" title="No es administrador">
                <a href="/main/inc/ajax/agenda.ajax.php?a=get_user_agenda&amp;user_id=4" class="agenda_opener">
                    <img src="/main/img/icons/22/month.png" alt="Calendario libre/ocupado" title="Calendario libre/ocupado">
                </a> 
            </td>
	</tr>
	</tbody>
    </table>';
    
    print $html->crearWrapper(null, null, null, $h3, $h4 ,$this->layout()->content, null,$contenido);
?>