<?php
$html= new Application_Model_Html();
$cursousuario=new Application_Model_CursosUsuario();
$cursos=new Application_Model_Cursos();
$listacursos=$cursos->listarCursosPeriodoActualActivos();
$contenido = '
<table class="data_table">
<thead>
<tr class="row_odd">
<th>&nbsp;</th>
<th>Codigo</th>
<th><a href="">Grado</a></th>
<th><a href="">Seccion</a></th>
<th><a href="">Curso</a></th>
<th><a href="">Descripcion</a></th>
<th><a href="">Accion</a></th>
</tr>
</thead> ';
foreach ($listacursos as $aux) {
        $contenido.=' <tr class="row_odd">
<td>
<input type="checkbox" name="id" value="' . $aux['iCursIdCursos'] . '">
</td>
<td>
<center>' . $aux['iCursIdCursos'] . '</center>
</td>
<td>
<center>' . $aux['vGradoDescripcion'] . '</center>
</td>
<td>
<center>' . $aux['vSeccDescripcion'] . '</center>
</td>
<td>
<center>' . $aux['vCursNombreCurso'] . '</center>
</td>
<td>
<center>' . $aux['iCursDescripcion'] . '</center>
</td>
<td>
<center>';
        $resultado=$cursos->obtenerdocentescurso($aux['iCursIdCursos'] );
    if ($resultado==NULL) {
        $contenido.='
<a onclick="modaldocente('.$aux['iCursIdCursos'].');" class="suscripcion" style="cursor:pointer" ><img id="img_4" src="/main/img/icons/22/user_subscribe_course.png" alt="Desactivar" title="Inscribir Docente"></a>
<a ><img src="/main/img/icons/22/unsubscribe_course_na.png" alt="Dar de Baja" title="Dar de Baja" /></a>
<a class="info"><img src="/main/img/icons/22/info.png " alt="Informacion Adicional" title="Informacion Docente" /></a>
';
    } else {
        $contenido.='<a onclick="modaldocente('.$aux['iCursIdCursos'].');" class="suscripcion" style="cursor:pointer" ><img id="img_4" src="/main/img/icons/22/wiki_assignment.png" alt="Desactivar" title="Quitar Docente"></a>
<a onclick="inscribedocente('.$resultado[0]['Usuarios_iUsuIdUsuario'].',\'del\','.$aux['iCursIdCursos'].')"><img src="/main/img/icons/22/unsubscribe_course.png" alt="Dar de Baja" title="Dar de Baja" /></a>
<a onclick="infoDocenteCurso('.$aux['iCursIdCursos'].');" class="info" id="info" style="cursor:pointer"><img src="/main/img/icons/22/info.png " alt="Informacion Adicional" title="Informacion Docente" /></a>
';
    }
    $contenido.='
</center>
</td>
</tr>';
}
$contenido .= '</tbody>
</table>';

  print $html->crearContentAjax($contenido);
?>