<?php

    $this->titulopagina='Los Pinos - Nuevo Apoderado';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();
    
    $mysession = new Zend_Session_Namespace('sesion');
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    $this->script='<script type="text/javascript" src="/js/codigito.js" > </script>
        <script type="text/javascript" src="/js/mascarainput.js" > </script>
        <script>$(document).ready(function(){
            $("#nombreusuario").validaTexto("usuario");
            $("#dni").validaTexto("dni");
            $("#dni").mask("99999999");
        });</script>';
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
   
    
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>';
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
           $h3.='
                    <a href="'.$aux['url'].'" target="_top">
                        <span id="tab_active">'.$aux['Descripcion'].'</span>
                    </a>
                </li>';
    }
    $h3 .= '</ul>';
    
    $h4='
            <ul class="bread">
                <li>
                    <a class="home" href="/">
                        <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                    </a>
                </li>
                <li>
                    <a href="usuarios" class="breadcrumb breadcrumb0" target="_top">
                        <span>Usuarios</span>
                    </a>
                </li>
                <li>
                    <a href="nuevoapoderado" class="breadcrumb breadcrumb1">
                        <span>Registrar Apoderado</span>
                    </a>
                </li>
            </ul>';
           
        $contenido = '
        <div class="admin_section formulario">
            <h4>Registrar Nuevo Apoderado</h4>'.$this->formularionuevoapoderado.'</div>';
        
       
        $contenido .= '
</div>';
    
    print $html->crearWrapper(null, null, null, $h3, $h4 ,$this->layout()->content, null,$contenido);
?>