<script type="text/javascript">   
     function cargarseccion(){
        var valor=$("#cbogrado").val();
            elem=document.getElementById('cboseccion');
            $("#cboseccion").html('<option>Cargando...</option>');
            var option;
            $.getJSON("listarsecciongrado/?codgrad="+valor, function(data){
                var seccion = data;var option;
                for (var x = 0 ; x < seccion.length ; x++) {
                    option+='<option value='+seccion[x].iSeccIdSeccion+'>'+seccion[x].vSeccDescripcion+'</option>';
                }
                 $("#cboseccion").html(option);
           });
        }    

</script>
<?php
    $this->titulopagina='Los Pinos - Nuevo Curso';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $h3 = '<ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='
        <ul class="bread">
            <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="cursos" class="breadcrumb breadcrumb0" target="_top">
                    <span>Cursos</span>
                </a>
            </li>
            <li>
                <a href="nuevocurso" class="breadcrumb breadcrumb1">
                    <span>Nuevo Curso</span>
                </a>
            </li>
        </ul>';
           
        $contenido = '
            <div class="admin_section treinta"> 
                <h4>Registrar Nuevo Curso</h4>'.$this->formularioagregarcurso.'</div>'.
            '
            <div class="admin_section setenta">
                <h4>Lista de Cursos</h4>';
        
        $cursos = new Application_Model_Cursos;
        $contenido .= $cursos->crearTablaCursosSimple();
        $contenido .= '
            </div>';
    
    print $html->crearWrapper(null, null, null, $h3, $h4 ,$this->layout()->content, null,$contenido);
?>