<?php
    $this->titulopagina='Los Pinos - Nuevo Docente';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();
    
//    $script='
//        <script type="text/javascript" src="/js/jquery.form.js" ></script>
//        <script type="text/javascript" src="/js/codigito.js" > </script>
//        <script type="text/javascript" src="/js/jquery-ui/jquery-ui-1.8.16.custom.min.js" > </script>
//        <script type="text/javascript">
//            $(document).ready(function() {
//            $("#formLogin").ajaxForm(function() {
//            $(".setenta").load("listadoseccionesajax");
//            });
//            });
//        </script>';
//    $this->script=$script;   
    
    $mysession = new Zend_Session_Namespace('sesion');
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
   
    
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>';
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
           $h3.='
                    <a href="'.$aux['url'].'" target="_top">
                        <span id="tab_active">'.$aux['Descripcion'].'</span>
                    </a>
                </li>';
    }
    $h3 .= '</ul>';
    
    $h4='
            <ul class="bread">
                <li>
                    <a class="home" href="/">
                        <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                    </a>
                </li>
                <li>
                    <a href="usuarios" class="breadcrumb breadcrumb0" target="_top">
                        <span>Usuarios</span>
                    </a>
                </li>
                <li>
                    <a href="nuevodocente" class="breadcrumb breadcrumb1">
                        <span>Registrar Docente</span>
                    </a>
                </li>
            </ul>';
           
        $contenido = '
        <div class="admin_section formulario">
            <h4>Registrar Nuevo Docente</h4>'.$this->formularionuevodocente.'</div>';
        
       
        $contenido .= '
</div>';
    
    print $html->crearWrapper(null, null, null, $h3, $h4 ,$this->layout()->content, null,$contenido);
?>