<?php
    $this->titulopagina='Los Pinos - Nueva Seccion';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $h3 = '<ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='
        <ul class="bread">
            <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="plataforma" class="breadcrumb breadcrumb0" target="_top">
                    <span>Plataforma</span>
                </a>
            </li>
            <li>
                <a href="nuevaseccion" class="breadcrumb breadcrumb1">
                    <span>Nueva Sección</span>
                </a>
            </li>
        </ul>';
           
        $contenido = '
            <div class="admin_section treinta"> 
                <h4>Registrar Nueva Seccion</h4>'.$this->formnuevaseccion.'</div>'.
            '
            <div class="admin_section setenta">
            <h4>Lista de Secciones</h4>';
        $seccion = new Application_Model_Seccion();
        $contenido .= $seccion->crearTablaSecciones();
        $contenido .= '</div>';
    
    print $html->crearWrapper(null, null, null, $h3, $h4 ,$this->layout()->content, null,$contenido);
?>