<?php
    $this->titulopagina='Los Pinos - Administracion de la Plataforma';
    $this->css='
        <link media="screen" rel="stylesheet" href="/css/colorbox.css" />';
    $this->script=' 
    	<script type="text/javascript" src="/js/colorbox/jquery.colorbox.js"></script>
    	<script>
        $(document).ready(function () {
            //Examples of how to assign the ColorBox event to elements
            $(".jqIframe").colorbox({ width: "90%", height: "90%", iframe: true });
            //Example of preserving a JavaScript event for inline calls.
            $("#click").click(function () {
                $("#click").css({ "background-color": "#f00", "color": "#fff", "cursor": "inherit" }).text("Abrir esta ventana de nuevo y este mensaje aún estará aqui.");
                return false;
            });
        });
	</script>';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="plataforma" class="breadcrumb breadcrumb0" target="_top">
                    <span>Plataforma</span>
                </a>
            </li>
        </ul>';
    $peraca= new Application_Model_PeriodoAcademico();
    $contenido = '
        <div class="admin_section">
            <h4><img src="/main/img/course.gif" alt="Cursos" title="Cursos"> Periodo Académico</h4>
            <ul>';
        if(!$peraca->validarPeriodo()){
            $contenido .= '<li><a style="text-decoration:line-through; color:#848484;">Actualizar Periodo Académico (No Disponible)</a></li>';
        }
        else{
            $contenido .= '<li><a href="actualizarperiodo">Actualizar Periodo Académico</a></li>';
        }
        $contenido .= '                
                <li><a href="course_list.php">Lista de cursos</a></li>
                <li><a href="course_export.php">Exportar cursos</a></li>
                <li><a href="course_import.php">Importar cursos desde un fichero</a></li>
                <li><a href="course_category.php">Categorías de cursos</a></li>
                <li><a href="subscribe_user2course.php">Inscribir usuarios en un curso</a></li>
            </ul>
        </div>
        <div class="admin_section">
            <h4><img src="/main/img/course.gif" alt="Grados" title="Grados"> Grado</h4>
             <ul>';
        if(!$peraca->validarActivarGrado()){
            $contenido .= '<li><a style="text-decoration:line-through; color:#848484;">Editar Grados (No Disponible)</a></li>';
        }
        else{
            $contenido .= '<li><a href="nuevogrado">Editar Grados</a></li>';
        }
        $contenido .= '
                <li><a href="configrados">Grados por Defecto</a></li>                
                <li><a href="course_export.php">Exportar cursos</a></li>
                <li><a href="course_import.php">Importar Seccion desde un fichero</a></li>
                <li><a href="course_category.php">Secciones por Grado</a></li>
                <li><a href="subscribe_user2course.php">Inscribir sección en un grado</a></li>
            </ul>
        </div>
        <div class="admin_section">
            <h4><img src="/main/img/course.gif" alt="Secciones" title="Secciones">Secciones</h4>
             <ul>';
         if(!$peraca->validarActivarSeccion()){
            $contenido .= '<li><a style="text-decoration:line-through; color:#848484;">Crear Sección (No Disponible)</a></li>';
            }
            else{
                $contenido .= '<li><a href="nuevaseccion">Crear Sección</a></li> ';
            }
        $contenido.='   
                <li><a class="jqIframe" href="pruebando">Grados por Defecto</a></li>                
                <li><a href="course_export.php">Exportar cursos</a></li>
                <li><a href="course_import.php">Importar Seccion desde un fichero</a></li>
                <li><a href="course_category.php">Secciones por Grado</a></li>
                <li><a href="subscribe_user2course.php">Inscribir sección en un grado</a></li>
            </ul>
        </div>';
    
    print $html->crearWrapper(null, null, null, $h3, $h4 ,null, null,$contenido);
?>

