 <head>
 	<meta charset="UTF-8">
 	<script type="text/javascript">
		var ln = 'es';
		
	</script>

	<script type="text/javascript" src="/tablero/js/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="/tablero/js/jquery.form.js"></script>
	<script type="text/javascript" src="/tablero/js/lib.min.js"></script>
	<script type="text/javascript" src="/tablero/js/es.js"></script>
	<script type="text/javascript" src="/tablero/js/main.min.js"></script>
	<link type="text/css" rel="stylesheet" href="/tablero/css/style.css">
</head>

<body class="es">

	<div id="container">

		

		<div id="menuContainer" class="clearfix">
			<div class="inner">
				<ul id="menu">
					<li class="active"><a href="javascript:;" class="addition" rel="+"><strong>Sumas</strong></a></li>
					<li class=""><a href="javascript:;" class="subtraction" rel="-"><strong>Restas</strong></a></li>
					<li class=""><a href="javascript:;" class="multiplication" rel="*"><strong>Multiplicaciones</strong></a></li>
					<li class=""><a href="javascript:;" class="division" rel="/"><strong>Divisiones</strong></a></li>
				</ul>
				<ul class="annonce">
					<li><a href="comparison/es.html" id="comparison"><strong>&lt; = &gt;</strong></a></li>
					<li><a href="clock/es.html" id="clock"><strong>Reloj y el tiempo</strong></a></li>
				</ul>
			</div>
		</div>

		<div id="wrapper">
			<div id="content">

				<div id="playground">
					<div class="status">
						<div class="gameBoard">
							<dl>
								<dt class="timeDisplay label" style="display: none; ">Tiempo:</dt>
								<dd class="timeDisplay time" style="display: none; ">00:30</dd>
								<dt>Preguntas respondidas:</dt>
								<dd class="answers" style="display: block; ">0</dd>
								<dt>Respuestas equivocadas:</dt>
								<dd class="errors" style="display: block; ">0</dd>
							</dl>
						</div>
						<strong class="total" style="display: inline; ">0</strong>&nbsp;puntos					</div>
					<div id="equation">
						<span id="operand_0_Holder"><input name="operand_0" type="text" id="operand_0" class="operand" title="Informa tu número y aprieta 'Enter'" readonly=""></span>
						<span id="operator" class="operatorHolder">+</span>
						<span id="operand_1_Holder"><input name="operand_1" type="text" id="operand_1" class="operand" title="Informa tu número y aprieta 'Enter'" readonly=""></span>
						<span class="operatorHolder">=</span>
						<span id="operand_2_Holder"><input name="operand_2" type="text" id="operand_2" class="operand answer active" title="Informa tu número y aprieta 'Enter'"></span>
					</div>
					<p id="messageWrapper"><span></span></p>
				</div>

			</div><!--content-->
		</div>

		<div id="navigation">
			<div class="inner">
<!--				<h2 class="headline">Practice Your Math</h2>-->
				<div class="clearfix box settings">
					<fieldset class="clearfix leftCol">
						<h3 class="title">Dificultad</h3>
		    			<ul class="clearfix rangeSelector range1">
							<li>
								<label for="range1_2" title="números 1 a 5">
									<input name="range1" id="range1_2" type="radio" value="1|5">
									Muy fácil								</label>
							</li>
							<li>
								<label for="range1_3" title="números 1 a 10">
									<input name="range1" id="range1_3" type="radio" value="1|10">
									Fácil								</label>
							</li>
							<li>
								<label for="range1_4" title="números 1 a 20">
									<input name="range1" id="range1_4" type="radio" value="1|20">
									Algo fácil								</label>
							</li>
							<li>
								<label for="range1_5" title="números 1 a 100">
									<input name="range1" id="range1_5" type="radio" value="1|100">
									No tan fácil								</label>
							</li>
						</ul>

						<div class="clearfix rangeSelector range2" style="display: none; ">
							<p>Elige los números</p>
							<p class="clearfix"><!--<label for="range2_start">Rango</label>-->
								<select name="range2_start" id="range2_start">
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="4">4</option>
									<option value="5">5</option>
									<option value="6">6</option>
									<option value="7">7</option>
									<option value="8">8</option>
									<option value="9">9</option>
								</select>
								, <select name="range2_end" id="range2_end">
									<option value="">---</option>
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="4">4</option>
									<option value="5">5</option>
									<option value="6">6</option>
									<option value="7">7</option>
									<option value="8">8</option>
									<option value="9">9</option>
								</select>
							</p>
						</div>
					</fieldset>


					<fieldset class="clearfix rightCol">
						<h3 class="title">Posición de la incógnita</h3>

						<ul class="clearfix positionSelector">
							<li class="xPosition1">
								<label for="xPosition1">
									<input name="xPosition" id="xPosition1" type="radio" value="3">
									<span>1 + 2 = <strong>__</strong></span>
								</label>
							</li>
							<li class="xPosition2">
								<label for="xPosition2">
									<input name="xPosition" id="xPosition2" type="radio" value="2">
									<span>1 + <strong>__</strong> = 3</span>
								</label>
							</li>
							<li class="xPosition3">
								<label for="xPosition3">
									<input name="xPosition" id="xPosition3" type="radio" value="1">
									<span><strong>__</strong> + 2 = 3</span>
								</label>
							</li>
						</ul>
					</fieldset>
				</div>



				<p class="actions clearfix call practice">Práctica:
					<a href="javascript:;" class="practice secondaryAction">Continuar</a>
					<a href="javascript:;" class="newGame secondaryAction1">Empieza aquí</a>
				</p>

				<div class="clearfix box call">
					<h3 class="title">¿Listo para empezar a probar tus habilidades matemáticas?</h3>
					<p class="tease clearfix">
						Elige el tiempo<br>
						<select name="xTime" id="xTime">
							<option value="30">30 segundos</option>
							<option value="45">45 segundos</option>
							<option value="60">1 minuto</option>
							<option value="75">1 minuto 15 segundos</option>
							<option value="90">1 minuto 30 segundos</option>
							<option value="120">2 minutos</option>
							<option value="180">3 minutos</option>
							<option value="240">4 minutos</option>
							<option value="300">5 minutos</option>
						</select>
					</p>
					<p class="actions clearfix">
						<a href="javascript:;" class="StartXTimeGame primaryAction">Empezar un juego nuevo</a>
					</p>
				</div>

				<p class="links clearfix">
					<a href="javascript:;" class="viewResult overlayTrigger" rel="#resultBox">Puntuación</a>
					<a href="javascript:;" class="viewHelp overlayTrigger" rel="#helpBox">Ayuda</a>
				</p>

			</div>
		</div>

		

		

		<!-- yes/no dialog -->
		<div class="modal" id="resultBox">
			<h2>Puntuación</h2>
			<h4 class="gameoverTime"></h4>

			<dl>
				<dt>Operación:</dt>
				<dd class="operation">1</dd>
				<dt>Rango:</dt>
				<dd>Números desde <span class="min"></span> a <span class="max"></span></dd>
				<dt>Tiempo:</dt>
				<dd class="gameTime">1</dd>
				<dt>puntos:</dt>
				<dd class="points">1</dd>
				<dt>Preguntas respondidas:</dt>
				<dd class="answers" style="display: block; ">0</dd>
				<dt>Respuestas equivocadas:</dt>
				<dd class="errors" style="display: block; ">0</dd>
			</dl>


			<!-- yes/no buttons -->
			<p class="actions"><a href="javascript:;" class="close secondaryAction1"> Cerrar </a></p>
		</div>


		<!-- help dialog -->
		<div class="modal" id="helpBox">
			<h2>Ayuda</h2>

			<p>Informa el número que piensas que es el correcto y aprienta la tecla <code>Enter</code> o el botón <code>Verificar</code>.</p>
			<p>Una respuesta correcta al primer intento te da cinco puntos, al segundo o tercero te da 3 puntos y un punto para los otros casos.</p>

			<!-- yes/no buttons -->
			<p class="actions"><a href="javascript:;" class="close secondaryAction1"> Cerrar </a></p>
		</div>

		<!-- overlayed element -->
		<div class="modal" id="MultiplicationTableOverlay">
			<h2>Tabla de multiplicar</h2>
			<!-- the external content is loaded inside this tag -->
			<div class="contentWrap"></div>
			<p class="actions"><a href="javascript:;" class="close secondaryAction1"> Cerrar </a></p>
		</div>


	</div>
 


<!-- Mirrored from math.cilenia.com/es by HTTrack Website Copier/3.x [XR&CO'2010], Wed, 09 Nov 2011 01:26:28 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8"><!-- /Added by HTTrack -->
</body>