<?php
    $this->titulopagina='Los Pinos - Usuarios';
    $this->css='
        <link media="screen" rel="stylesheet" href="/css/colorbox.css" />';
    $this->script=' 
    	<script type="text/javascript" src="/js/colorbox/jquery.colorbox.js"></script>
    	<script>
        $(document).ready(function () {
            //Examples of how to assign the ColorBox event to elements
            $(".jqIframe").colorbox({ width: "90%", height: "90%", iframe: true });
            //Example of preserving a JavaScript event for inline calls.
            $("#click").click(function () {
                $("#click").css({ "background-color": "#f00", "color": "#fff", "cursor": "inherit" }).text("Abrir esta ventana de nuevo y este mensaje aún estará aqui.");
                return false;
            });
        });
	</script>';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="usuarios" class="breadcrumb breadcrumb0" target="_top">
                    <span>Usuarios</span>
                </a>
            </li>
        </ul>';
    $peraca= new Application_Model_PeriodoAcademico();
    $contenido = '
        <div class="admin_section treinta">
            <h4><img src="/main/img/members.gif" alt="Cursos" title="Cursos"> Usuarios</h4>
            <ul>               
                <li><a href="listausuarios">Lista de Usuarios</a></li>
                <li><a href="nuevoalumno">Registrar Alumno</a></li>
                <li><a href="nuevodocente">Registrar Docente</a></li>
                <li><a href="nuevoapoderado">Registrar Apoderado</a></li>
                <li><a href="nuevodirector">Registrar Director</a></li>
                <li><a href="buscarusuario">Editar Usuarios</a></li>
            </ul>
        </div>';
    
    print $html->crearWrapper(null, null, null, $h3, $h4 ,null, null,$contenido);
?>

